# Generated by Django 5.2.15 on 2026-07-06 04:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RasterDataset',
            fields=[
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, max_length=40, primary_key=True, serialize=False)),
                ('dataset_name', models.CharField(default='Unknown Dataset Name', max_length=90, verbose_name='Human Readable Dataset Short Name')),
                ('dataset_subtype', models.CharField(default='Unknown_Dataset_Subtype', help_text='Used by the pipeline to select which sub type script logic is used.', max_length=90, verbose_name='Dataset Subtype')),
                ('is_pipeline_enabled', models.BooleanField(default=False, help_text='Is this ETL Dataset enabled for pipeline processing?')),
                ('is_pipeline_active', models.BooleanField(default=False, help_text='Is an ETL job currently running for this dataset?')),
                ('merge_only', models.BooleanField(default=False, help_text='Skip standard ETL and proceed straight to merging NC4 files?')),
                ('tds_product_name', models.CharField(default='UNKNOWN_PRODUCT_NAME', max_length=90, verbose_name='(TDS) Product Name')),
                ('tds_region', models.CharField(default='UNKNOWN_REGION', max_length=90, verbose_name='(TDS) Region')),
                ('tds_spatial_resolution', models.CharField(default='UNKNOWN_SPATIAL_RESOLUTION', max_length=90, verbose_name='(TDS) Spatial Resolution')),
                ('tds_temporal_resolution', models.CharField(default='UNKNOWN_TEMPORAL_RESOLUTION', max_length=90, verbose_name='(TDS) Temporal Resolution')),
                ('temp_working_dir', models.TextField(default='', verbose_name='(Path) Local temp working directory')),
                ('final_load_dir', models.TextField(default='', verbose_name='(Path) Local NC4 directory')),
                ('fast_directory_path', models.TextField(default='', verbose_name='(Path) Merge Directory')),
                ('nc4_verification_path', models.TextField(blank=True, default='', verbose_name='(Path) NC4 Verification')),
                ('merged_verification_path', models.TextField(blank=True, default='', verbose_name='(Path) Merged Verification')),
                ('late_after', models.IntegerField(default=0, help_text='Duration in days')),
                ('number', models.IntegerField(default=0, help_text='Datatype number')),
                ('merge_type', models.CharField(blank=True, default='None', help_text='Monthly, Yearly, or None.', max_length=10, verbose_name='Merge Type')),
                ('dataset_information', models.JSONField(blank=True, default=dict, help_text='JSON configuration driving all ETL behavior.', verbose_name='NC4 Attributes Data')),
                ('dataset_type', models.CharField(blank=True, choices=[('time_series', 'Time Series'), ('static', 'Static')], help_text='Time-series (has temporal dimension) or static (fixed in time).', max_length=20, null=True)),
                ('data_category', models.CharField(choices=[('observational', 'Observational'), ('forecast', 'Forecast'), ('observational_and_forecast', 'Observational & Forecast')], default='observational', max_length=30)),
                ('data_type', models.CharField(choices=[('raster', 'Raster'), ('point', 'Point')], default='raster', max_length=10)),
            ],
            options={
                'verbose_name': 'Raster Dataset',
                'verbose_name_plural': 'Raster Datasets',
                'db_table': 'dataagent_raster_dataset',
            },
        ),
        migrations.CreateModel(
            name='VectorDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('level', models.IntegerField(blank=True, choices=[(0, 'Countries'), (1, 'States'), (2, 'Counties')], null=True)),
                ('source_url', models.TextField(blank=True, default='')),
                ('schema_name', models.CharField(default='dataagent', max_length=100)),
                ('table_name', models.CharField(default='admin', max_length=100)),
                ('is_loaded', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vector Dataset',
                'verbose_name_plural': 'Vector Datasets',
                'db_table': 'dataagent_vector_dataset',
            },
        ),
        migrations.CreateModel(
            name='CategoricalRasterLegend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raster_dataset_name', models.CharField(db_index=True, max_length=100)),
                ('band_value', models.IntegerField()),
                ('code', models.CharField(blank=True, max_length=20)),
                ('label', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'dataagent_categorical_raster_legend',
                'indexes': [models.Index(fields=['raster_dataset_name', 'code'], name='dataagent_c_raster__18dd70_idx')],
                'unique_together': {('raster_dataset_name', 'band_value')},
            },
        ),
        migrations.CreateModel(
            name='DataFetchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_name', models.CharField(default='dataagent', max_length=100)),
                ('bbox_west', models.FloatField()),
                ('bbox_south', models.FloatField()),
                ('bbox_east', models.FloatField()),
                ('bbox_north', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('transforming', 'Transforming'), ('loading', 'Loading to PostGIS'), ('combining', 'Combining Datasets'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('progress_pct', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('dates_loaded', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raster_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_jobs', to='data_agent.rasterdataset')),
            ],
            options={
                'db_table': 'dataagent_data_fetch_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dataagent_config',
                'unique_together': {('user', 'key')},
            },
        ),
    ]
