# Generated by Django 5.2.15 on 2026-07-06 04:28

import django.contrib.postgres.fields
import django.contrib.postgres.search
import django.db.models.deletion
import knowledge_agent.models
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # These tables live in a dedicated `knowledge` PostgreSQL schema (each
        # model's Meta.db_table is schema-qualified via _schema_table, e.g.
        # `knowledge"."knowledge_chunks`). `makemigrations` does NOT emit the
        # schema/extension setup, so it is hand-authored here and MUST be
        # re-added as the FIRST operation if these migrations are ever
        # regenerated — otherwise `migrate` fails on a clean DB with
        # 'schema "knowledge" does not exist'. Kept in a migration (not only the
        # dev postgres/init-extensions.sh, which runs only for local Compose) so
        # schema creation stays portable to production/K8s. See
        # knowledge_agent/documentation/architecture.md.
        migrations.RunSQL(
            sql=(
                "CREATE SCHEMA IF NOT EXISTS knowledge; "
                "CREATE EXTENSION IF NOT EXISTS vector; "
                "CREATE EXTENSION IF NOT EXISTS pg_trgm;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.TextField(default=knowledge_agent.models._uuid_str, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('content_tsv', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('content', config='english'), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'knowledge"."knowledge_chunks',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEntity',
            fields=[
                ('id', models.TextField(default=knowledge_agent.models._uuid_str, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('entity_type', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'knowledge"."knowledge_entities',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeTenant',
            fields=[
                ('id', models.CharField(help_text="The tenant_id slug — e.g. 'legal', 'agronomy'. Pattern: lowercase letters, digits, underscore, dash.", max_length=64, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('default_strategy', models.CharField(default='hybrid', max_length=32)),
                ('domain', models.JSONField(blank=True, default=dict)),
                ('raptor_config_hash', models.CharField(blank=True, default='', max_length=64)),
                ('graphrag_config_hash', models.CharField(blank=True, default='', max_length=64)),
                ('ontology_config_hash', models.CharField(blank=True, default='', max_length=64)),
                ('raptor_dirty', models.BooleanField(default=False)),
                ('graphrag_dirty', models.BooleanField(default=False)),
                ('ontology_dirty', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knowledge"."knowledge_tenants',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('path', models.TextField()),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('agent_label', models.CharField(blank=True, default='default', max_length=64)),
                ('last_ingested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='knowledge_agent.knowledgetenant')),
            ],
            options={
                'db_table': 'knowledge"."knowledge_sources',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeRelationship',
            fields=[
                ('id', models.TextField(default=knowledge_agent.models._uuid_str, primary_key=True, serialize=False)),
                ('relationship', models.TextField()),
                ('weight', models.FloatField(default=1.0)),
                ('source_chunk_id', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_entity', models.ForeignKey(blank=True, db_column='source_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='knowledge_agent.knowledgeentity')),
                ('target_entity', models.ForeignKey(blank=True, db_column='target_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='knowledge_agent.knowledgeentity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='knowledge_agent.knowledgetenant')),
            ],
            options={
                'db_table': 'knowledge"."knowledge_relationships',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeRaptorNode',
            fields=[
                ('id', models.TextField(default=knowledge_agent.models._uuid_str, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('level', models.IntegerField(default=0)),
                ('parent_id', models.TextField(blank=True, null=True)),
                ('children_ids', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raptor_nodes', to='knowledge_agent.knowledgetenant')),
            ],
            options={
                'db_table': 'knowledge"."knowledge_raptor_nodes',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeParentChunk',
            fields=[
                ('id', models.TextField(default=knowledge_agent.models._uuid_str, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_chunks', to='knowledge_agent.knowledgetenant')),
            ],
            options={
                'db_table': 'knowledge"."knowledge_parent_chunks',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeOntology',
            fields=[
                ('id', models.TextField(default=knowledge_agent.models._uuid_str, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('turtle_data', models.TextField()),
                ('source_chunk_ids', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ontologies', to='knowledge_agent.knowledgetenant')),
            ],
            options={
                'db_table': 'knowledge"."knowledge_ontology',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeIngestionRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('pipelines_run', models.JSONField(blank=True, default=list, help_text='Names of pipeline stages executed: chunk_and_embed, build_contextual, build_parent_child, build_graph, build_raptor, build_ontology.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chunks_created', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(blank=True, help_text='Null means the run targeted all sources for the tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_runs', to='knowledge_agent.knowledgesource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_runs', to='knowledge_agent.knowledgetenant')),
            ],
            options={
                'db_table': 'knowledge"."knowledge_ingestion_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeIngestionPartial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('branch', models.CharField(help_text="Pipeline branch name: 'ontology', 'raptor_summary', etc.", max_length=32)),
                ('chunk_id', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partials', to='knowledge_agent.knowledgeingestionrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_partials', to='knowledge_agent.knowledgetenant')),
            ],
            options={
                'db_table': 'knowledge"."knowledge_ingestion_partials',
            },
        ),
        migrations.AddField(
            model_name='knowledgeentity',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='knowledge_agent.knowledgetenant'),
        ),
        migrations.CreateModel(
            name='KnowledgeConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_configs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_configs', to='knowledge_agent.knowledgetenant')),
            ],
            options={
                'db_table': 'knowledge_config',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunkContextual',
            fields=[
                ('id', models.TextField(default=knowledge_agent.models._uuid_str, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('context_prefix', models.TextField(blank=True, default='')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('content_tsv', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('content', config='english'), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_chunk', models.ForeignKey(blank=True, db_column='base_chunk_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contextual_copies', to='knowledge_agent.knowledgechunk')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contextual_chunks', to='knowledge_agent.knowledgetenant')),
            ],
            options={
                'db_table': 'knowledge"."knowledge_chunks_contextual',
            },
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_agent.knowledgetenant'),
        ),
        migrations.CreateModel(
            name='KnowledgeChildChunk',
            fields=[
                ('id', models.TextField(default=knowledge_agent.models._uuid_str, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge_agent.knowledgeparentchunk')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_chunks', to='knowledge_agent.knowledgetenant')),
            ],
            options={
                'db_table': 'knowledge"."knowledge_child_chunks',
            },
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.UniqueConstraint(fields=('tenant', 'path'), name='uq_source_tenant_path'),
        ),
        migrations.AddIndex(
            model_name='knowledgerelationship',
            index=models.Index(fields=['tenant'], name='idx_rel_tenant'),
        ),
        migrations.AddConstraint(
            model_name='knowledgerelationship',
            constraint=models.UniqueConstraint(fields=('tenant', 'source_entity', 'target_entity', 'relationship', 'source_chunk_id'), name='uq_rel_tenant_endpoints_rel_chunk'),
        ),
        migrations.AddIndex(
            model_name='knowledgeraptornode',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_raptor_embedding', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='knowledgeraptornode',
            index=models.Index(fields=['tenant'], name='idx_raptor_tenant'),
        ),
        migrations.AddIndex(
            model_name='knowledgeparentchunk',
            index=models.Index(fields=['tenant'], name='idx_parent_tenant'),
        ),
        migrations.AddIndex(
            model_name='knowledgeontology',
            index=models.Index(fields=['tenant'], name='idx_ontology_tenant'),
        ),
        migrations.AddIndex(
            model_name='knowledgeingestionpartial',
            index=models.Index(fields=['tenant', 'run', 'branch'], name='idx_partial_run_branch'),
        ),
        migrations.AddIndex(
            model_name='knowledgeentity',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_entity_embedding', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='knowledgeentity',
            index=models.Index(fields=['tenant'], name='idx_entity_tenant'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeentity',
            constraint=models.UniqueConstraint(fields=('tenant', 'name', 'entity_type'), name='uq_entity_tenant_name_type'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgeconfig',
            unique_together={('tenant', 'user', 'key')},
        ),
        migrations.AddIndex(
            model_name='knowledgechunkcontextual',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_ctx_chunks_embedding', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='knowledgechunkcontextual',
            index=models.Index(fields=['tenant'], name='idx_ctx_chunks_tenant'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_chunks_embedding', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['tenant'], name='idx_chunks_tenant'),
        ),
        migrations.AddIndex(
            model_name='knowledgechildchunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_child_embedding', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='knowledgechildchunk',
            index=models.Index(fields=['tenant'], name='idx_child_tenant'),
        ),
    ]
