# Generated by Django 5.2.15 on 2026-07-06 04:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LangGraphCheckpoint',
            fields=[
                ('thread_id', models.TextField()),
                ('checkpoint_ns', models.TextField()),
                ('checkpoint_id', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'checkpoints',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LangGraphCheckpointBlob',
            fields=[
                ('thread_id', models.TextField()),
                ('checkpoint_ns', models.TextField()),
                ('channel', models.TextField(primary_key=True, serialize=False)),
                ('version', models.TextField()),
            ],
            options={
                'db_table': 'checkpoint_blobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LangGraphCheckpointWrite',
            fields=[
                ('thread_id', models.TextField()),
                ('checkpoint_ns', models.TextField()),
                ('checkpoint_id', models.TextField()),
                ('task_id', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'checkpoint_writes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('agent_state', models.JSONField(blank=True, default=dict)),
                ('agent_memory', models.JSONField(blank=True, default=dict)),
                ('is_processing', models.BooleanField(default=False)),
                ('enabled_agents', models.JSONField(blank=True, default=list, help_text="List of agent_labels allowed for this chat's orchestrator. Empty list = all discovered agents enabled.")),
                ('agents_locked', models.BooleanField(default=False, help_text="When True, `enabled_agents` cannot be changed after creation. Used by callers that want to hard-pin a chat's agent scope at creation time.")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_chat',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatExperiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('experiment_id', models.UUIDField(help_text='SimulationAgent ExperimentSession PK')),
                ('experiment_type', models.CharField(default='single', max_length=16)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('is_baseline', models.BooleanField(default=False)),
                ('params_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='earthrise_agents_base.chat')),
            ],
            options={
                'db_table': 'chat_chatexperiment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed'), ('interrupted', 'Interrupted')], default='completed', max_length=15)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('current_node', models.CharField(blank=True, max_length=255, null=True)),
                ('artifacts', models.JSONField(blank=True, default=list, help_text='Visual artifacts from subagents (charts, maps, tables, etc.)')),
                ('interrupt_data', models.JSONField(blank=True, default=dict)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='earthrise_agents_base.chat')),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('plan_summary', models.TextField(blank=True)),
                ('plan_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='earthrise_agents_base.message')),
            ],
            options={
                'db_table': 'chat_executionplan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chart_type', models.CharField(choices=[('line', 'Line Chart'), ('bar', 'Bar Chart'), ('scatter', 'Scatter Plot'), ('pie', 'Pie Chart'), ('heatmap', 'Heatmap')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='earthrise_agents_base.message')),
            ],
            options={
                'db_table': 'chat_chart',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_email', models.EmailField(blank=True, default='', max_length=254)),
                ('category', models.CharField(choices=[('feature_suggestion', 'Feature Suggestion'), ('usability_issue', 'Usability Issue'), ('technical_issue', 'Technical Issue'), ('general_feedback', 'General Feedback'), ('praise', 'Praise'), ('data_quality', 'Data Quality Concern')], db_index=True, max_length=32)),
                ('content', models.TextField()),
                ('page_url', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('archived', 'Archived')], db_index=True, default='new', max_length=16)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feedback', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_site_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubagentTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_key', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('agent', models.CharField(help_text='data/knowledge/simulation/llm', max_length=20)),
                ('skill', models.CharField(max_length=100)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('depends_on', models.JSONField(blank=True, default=list, help_text='List of task_key strings')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=15)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_critical', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='earthrise_agents_base.executionplan')),
            ],
            options={
                'db_table': 'chat_subagenttask',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[('up', 'Thumbs Up'), ('down', 'Thumbs Down')], max_length=4)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_feedback', to='earthrise_agents_base.chat')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='earthrise_agents_base.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_message_feedback',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'message')},
            },
        ),
    ]
